#Шаблон для .env файла
Django config
SECRET_KEY=
DEBUG=True
DJANGO_ALLOWED_HOSTS=

Database config
DB_ENGINE=django.db.backends.postgresql
POSTGRES_DB=
POSTGRES_PASSWORD=
POSTGRES_USER=
POSTGRES_NAME=
POSTGRES_HOST=
POSTGRES_PORT=